name: rationarr

services:
  rationarr-app:
    image: rationarr-app
    container_name: rationarr-app
    hostname: rationarr-app
    ports:
      - "8000:8000"
    environment:
      PROWLARR_HOST: "${PROWLARR_HOST:-rationarr-prwlr}"
      PROWLARR_APIKEY: "${PROWLARR_APIKEY}" 
      DATABASE_URI: "postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST:-rationarr-db}:${POSTGRES_PORT:-5432}/${POSTGRES_DB:-rationarr}"
    depends_on:
      - rationarr-db

  rationarr-db:
    image: postgres:17
    container_name: rationarr-db
    hostname: rationarr-db
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB:-rationarr}"
    ports:
      - "5432:5432"
    volumes:
      - rationarr_pgdata:/var/lib/postgresql/data

volumes:
  rationarr_pgdata:
