name: rationarr

services:
  rationarr-app:
    image: "ghcr.io/peterbuga/rationarr"
    container_name: rationarr-app
    hostname: rationarr-app
    healthcheck:
      test: "curl -sf http://localhost:8000/api/health || exit 1"
      interval: "120s"
      retries: 5
      timeout: "10s"
      start_period: "60s"
      start_interval: "60s"
    ports:
      - "8000:8000"
    environment:
      PROWLARR_HOST: "${PROWLARR_HOST}"
      PROWLARR_APIKEY: "${PROWLARR_APIKEY}"
      FLARESOULVERR_URL: "${FLARESOULVERR_URL}"
      DATABASE_URI: "postgresql+asyncpg://${POSTGRES_USER:-rationarr}:${POSTGRES_PASSWORD:-rationarr}@${POSTGRES_HOST:-rationarr-db}:${POSTGRES_PORT}/${POSTGRES_DB:-rationarr}"
    depends_on:
      - rationarr-db

  rationarr-db:
    image: postgres:17
    container_name: rationarr-db
    hostname: rationarr-db
    environment:
      POSTGRES_USER: "${POSTGRES_USER:-rationarr}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-rationarr}"
      POSTGRES_DB: "${POSTGRES_DB:-rationarr}"
    # ports:
    #   - "5432:5432"
    volumes:
      - rationarr_pgdata:/var/lib/postgresql/data

volumes:
  rationarr_pgdata:
