"""indexer-login-columns

Revision ID: 0417fe421da6
Revises: 07e422a5e26c
Create Date: 2025-08-21 11:19:34.619773

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "0417fe421da6"
down_revision = "07e422a5e26c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("indexer", sa.Column("username", sa.String(), nullable=True))
    op.add_column("indexer", sa.Column("password", sa.String(), nullable=True))
    op.add_column("indexer", sa.Column("mfa_key", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("indexer", "mfa_key")
    op.drop_column("indexer", "password")
    op.drop_column("indexer", "username")
    # ### end Alembic commands ###
