"""scraper_updated_at_column

Revision ID: 07e422a5e26c
Revises: 93f0a2804544
Create Date: 2025-06-27 08:01:43.487583

"""

import sqlalchemy as sa

import app
from alembic import op

# revision identifiers, used by Alembic.
revision = "07e422a5e26c"
down_revision = "93f0a2804544"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "scraper",
        sa.Column("updated_at", app.db.utc_date_time.UtcDateTime(), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("scraper", "updated_at")
    # ### end Alembic commands ###
