"""scraper_table

Revision ID: 4cd1c67de1ff
Revises: 8e2bcefc72ea
Create Date: 2025-06-26 13:59:51.459903

"""

import sqlalchemy as sa

import app
from alembic import op

# revision identifiers, used by Alembic.
revision = "4cd1c67de1ff"
down_revision = "8e2bcefc72ea"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "scraper",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("indexer_id", sa.Uuid(), nullable=True),
        sa.Column("attribute", sa.String(), nullable=True),
        sa.Column("value", sa.String(), nullable=True),
        sa.Column(
            "created_at", app.db.utc_date_time.UtcDateTime(), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["indexer_id"],
            ["indexer.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_scraper_id"), "scraper", ["id"], unique=False)
    op.create_index(
        op.f("ix_scraper_indexer_id"), "scraper", ["indexer_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_scraper_indexer_id"), table_name="scraper")
    op.drop_index(op.f("ix_scraper_id"), table_name="scraper")
    op.drop_table("scraper")
    # ### end Alembic commands ###
