"""Indexer cascade deletes

Revision ID: 50b3c3fbed87
Revises: b90cb62ae6a1
Create Date: 2025-10-06 10:09:53.009382

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "50b3c3fbed87"
down_revision = "b90cb62ae6a1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("activity_indexer_id_fkey"), "activity", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "activity", "indexer", ["indexer_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint(
        op.f("scraper_indexer_id_fkey"), "scraper", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "scraper", "indexer", ["indexer_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "scraper", type_="foreignkey")
    op.create_foreign_key(
        op.f("scraper_indexer_id_fkey"),
        "scraper",
        "indexer",
        ["indexer_id"],
        ["id"],
    )
    op.drop_constraint(None, "activity", type_="foreignkey")
    op.create_foreign_key(
        op.f("activity_indexer_id_fkey"),
        "activity",
        "indexer",
        ["indexer_id"],
        ["id"],
    )
    # ### end Alembic commands ###
