"""add indexer.exchange_points column

Revision ID: 8da41d3eafa4
Revises: ec945cf9f394
Create Date: 2025-09-29 16:55:43.479619

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "8da41d3eafa4"
down_revision = "ec945cf9f394"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "indexer", sa.Column("exchange_points", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("indexer", "exchange_points")
    # ### end Alembic commands ###
