"""db init2

Revision ID: 8e2bcefc72ea
Revises:
Create Date: 2025-06-26 10:21:33.618424

"""

import sqlalchemy as sa

import app
from alembic import op

# revision identifiers, used by Alembic.
revision = "8e2bcefc72ea"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tracker",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("alias", sa.String(), nullable=True),
        sa.Column("url", sa.String(), nullable=True),
        sa.Column("api_key", sa.String(), nullable=True),
        sa.Column("cookie", sa.String(), nullable=True),
        sa.Column("created_at", app.db.utc_date_time.UtcDateTime(), nullable=False),
        sa.Column("updated_at", app.db.utc_date_time.UtcDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tracker_id"), "tracker", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tracker_id"), table_name="tracker")
    op.drop_table("tracker")
    # ### end Alembic commands ###
