"""indexer_type_column

Revision ID: 93f0a2804544
Revises: 4cd1c67de1ff
Create Date: 2025-06-27 06:44:39.794498

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "93f0a2804544"
down_revision = "4cd1c67de1ff"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("indexer", sa.Column("type", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("indexer", "type")
    # ### end Alembic commands ###
