"""add indexer active column

Revision ID: 98b6586c563d
Revises: c302a8edfd24
Create Date: 2025-08-21 12:20:12.849372

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "98b6586c563d"
down_revision = "c302a8edfd24"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("indexer", sa.Column("active", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("indexer", "active")
    # ### end Alembic commands ###
