"""add activity table

Revision ID: b90cb62ae6a1
Revises: 8da41d3eafa4
Create Date: 2025-09-29 17:18:50.509875

"""

import sqlalchemy as sa

import app
from alembic import op

# revision identifiers, used by Alembic.
revision = "b90cb62ae6a1"
down_revision = "8da41d3eafa4"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "activity",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("indexer_id", sa.Uuid(), nullable=True),
        sa.Column("activity", sa.String(), nullable=True),
        sa.Column(
            "created_at", app.db.utc_date_time.UtcDateTime(), nullable=False
        ),
        sa.Column(
            "updated_at", app.db.utc_date_time.UtcDateTime(), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["indexer_id"],
            ["indexer.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_activity_id"), "activity", ["id"], unique=False)
    op.create_index(
        op.f("ix_activity_indexer_id"), "activity", ["indexer_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_activity_indexer_id"), table_name="activity")
    op.drop_index(op.f("ix_activity_id"), table_name="activity")
    op.drop_table("activity")
    # ### end Alembic commands ###
