"""remove indexer alias column

Revision ID: c302a8edfd24
Revises: 0417fe421da6
Create Date: 2025-08-21 11:36:30.408110

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "c302a8edfd24"
down_revision = "0417fe421da6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("indexer", "alias")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "indexer",
        sa.Column("alias", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
