"""indexer non nulls

Revision ID: ec945cf9f394
Revises: 98b6586c563d
Create Date: 2025-08-21 12:22:13.023123

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "ec945cf9f394"
down_revision = "98b6586c563d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "indexer", "type", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "indexer", "url", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "indexer", "active", existing_type=sa.BOOLEAN(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "indexer", "active", existing_type=sa.BOOLEAN(), nullable=True
    )
    op.alter_column("indexer", "url", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column(
        "indexer", "type", existing_type=sa.VARCHAR(), nullable=True
    )
    # ### end Alembic commands ###
